#!/usr/bin/python

import random, time, math, sys

bases = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
def baseN(num,b):
	return ((num == 0) and  '0' ) or ( baseN(num // b, b).lstrip('0') + bases[num % b])

def password(base, length):
	base = max(10, min(len(bases), base))
	length = min(max(5, length), 20)
	"""	x = random.Random()
	x.seed(time.time())
	print base, length, x.randint(0, 10**int(math.log(length, 10)))
	return baseN(x.randint(0, 10**int(math.log(base, 10)*length)), base)"""
	x = random.Random()
	x.seed(time.time())
	return ''.join([bases[x.randint(0, base)] for i in range(length)])
		

if __name__ == '__main__':
	print password(62, 8)
